Repository Zywave/booster, pull requests merged in 2022-10, with the labels that each got.

#264 fix: force code blocks with long lines to wrap
  src/_includes/assets/styles/components/code-prismjs.scss
  src/_includes/assets/styles/layout/base.scss
Labels: bug

#269 chore: fix content widths
  src/_includes/assets/scripts/web-components/quick-links.ts
  src/_includes/assets/styles/components/side-nav.scss
  src/_includes/assets/styles/layout/base.scss
  src/_includes/assets/styles/layout/component.scss
  src/_includes/layouts/base.njk
  src/_includes/layouts/blog.njk
Labels: Booster site

#271 Update dev doc “web-components-in-react”
  src/_areas/design-system/developers/web-components-in-react.md
Labels: netlify-cms/pending_review
