Repository Zywave/booster, pull requests merged in 2022-04, with the labels that each got.

#194 Create Patterns doc “empty-states”
  src/_areas/design-system/patterns/empty-states.md
  static/images/emptystate_anatomy.svg
  static/images/emptystate_largespace_card.svg
  static/images/emptystate_largespace_centered.svg
  static/images/emptystate_largespace_text.svg
  static/images/emptystate_smallspace_centered.svg
  static/images/emptystate_table.svg
  static/images/emptystate_usage.svg
  static/images/firstuse_centered.svg
  static/images/firstuse_mobile.svg
  static/images/firstuse_table.svg
  static/images/firstuse_table2.svg
  static/images/imageplaceholder.svg
  static/images/imageplaceholder_mobile.svg
  static/images/noresults.svg
  static/images/noresults_mobile.svg
  static/images/usercleared.svg
  static/images/usercleared_mobile.svg
Labels: netlify-cms/pending_publish

#203 Update component “shell”
  src/_areas/application-framework/components/shell.md
Labels: netlify-cms/pending_publish

#141 Update component “buttons”
  src/_areas/design-system/components/buttons.md
  static/images/button-docs-anatomy.png
  static/images/button-docs-block-level-button.png
  static/images/button-docs-button-icon.png
  static/images/button-docs-destructivelink.svg
  static/images/button-docs-destructiveprimary.png
  static/images/button-docs-destructiveprimary.svg
  static/images/button-docs-destructivesecondary.svg
  static/images/button-docs-iconbutton.png
  static/images/button-docs-linkbutton.png
  static/images/button-docs-loadingstate.png
  static/images/button-docs-overflowicon.png
  static/images/button-docs-primarybutton.png
  static/images/button-docs-secondarybutton.png
  static/images/button-docs-states-bluebg.png
  static/images/button-docs-states.png
  static/images/button-docs-usage.png
Labels: netlify-cms/pending_publish

#166 Update component “file-inputs”
  src/_areas/design-system/components/file-inputs.md
  static/images/file-input_action-do-not.svg
  static/images/file-input_action-do.svg
  static/images/file-input_anatomy.svg
  static/images/file-input_draganddrop.svg
  static/images/file-input_form-do-not.svg
  static/images/file-input_form-do.svg
  static/images/file-input_form.svg
  static/images/file-input_icon.svg
  static/images/file-input_mobile.svg
  static/images/file-input_states.svg
  static/images/file-input_usage.svg
Labels: netlify-cms/pending_publish

#187 Update component “checkboxes”
  src/_areas/design-system/components/checkboxes.md
  static/images/anatomy-gallery.png
  static/images/anatomy-gallery.svg
  static/images/anatomy-standard.svg
  static/images/checkbox-types.png
  static/images/checkbox-types.svg
  static/images/do1.svg
  static/images/do2.svg
  static/images/do3.svg
  static/images/do4.svg
  static/images/don-t1.svg
  static/images/don-t2.svg
  static/images/don-t3.svg
  static/images/don-t4.svg
  static/images/gallery-checkbox-states-no-illustrations.svg
  static/images/gallery-checkbox-states.png
  static/images/gallery-checkbox-states.svg
  static/images/standard-checkbox-states.svg
Labels: netlify-cms/pending_publish

#206 feat: introduction section
  src/_areas/application-framework/developers/installation.md
  src/_areas/design-system/developers/installation.md
  src/_areas/design-system/patterns/empty-states.md
  src/_areas/design-system/visuals/colors.md
  src/_areas/introduction/about.md
  src/_areas/introduction/contributing/contribute-to-docs.md
  src/_areas/introduction/getting-started/how-to-get-started.md
  src/_areas/introduction/getting-started/installing-packages.md
  src/_areas/introduction/getting-started/what-is-shell.md
  src/_includes/assets/scripts/web-components/docs-grid.ts
  src/_includes/assets/scripts/web-components/docs-spacer.ts
  src/_includes/assets/styles/components/docs-fouc.scss
  src/_includes/assets/styles/components/table.scss
  src/_includes/assets/styles/global-styles.scss
  src/_includes/assets/styles/pages/colors.scss
  src/_includes/assets/styles/utils/_functions.scss
  src/_includes/components/top-nav.njk
  src/_pages/index.md
  static/images/foundations/colors/Blue_500.svg
  static/images/foundations/colors/Gray_200.svg
  static/images/foundations/colors/Green_500.svg
  static/images/foundations/colors/Purple_500.svg
  static/images/foundations/colors/Red_500.svg
  static/images/foundations/colors/Yellow_500.svg
  static/images/introduction/booster-ecosystem.png
  static/images/introduction/zui-shell-vs-zywave-shell.png
Labels: documentation

#210 Create Introduction “glossary/index”
  src/_areas/introduction/glossary/index.md
Labels: netlify-cms/draft

#212 Update component “buttons”
  src/_areas/design-system/components/buttons.md
Labels: netlify-cms/pending_publish
