Repository Zywave/booster, pull requests merged in 2023-08, with the labels that each got.

#278 Update Introduction “contributing/contribute-to-docs/index”
  src/_areas/introduction/contributing/contribute-to-docs/index.md
Labels: netlify-cms/pending_review

#308 Update component “tooltips”
  src/_areas/design-system/components/tooltips.md
  src/_includes/assets/scripts/web-components/docs-do-not.ts
  src/_includes/assets/scripts/web-components/docs-do.ts
  src/_includes/assets/styles/base/typography.scss
  src/_includes/assets/styles/components/docs-fouc.scss
  src/_includes/assets/styles/components/footer.scss
  src/_includes/assets/styles/components/side-nav.scss
  src/_includes/assets/styles/pages/blog.scss
  src/_includes/assets/styles/utils/_variables.scss
Labels: netlify-cms/draft

#306 Create Patterns doc “data-visualization”
  src/_areas/design-system/patterns/data-visualization.md
  static/images/bar-chart-annotation.svg
  static/images/bar-chart-do-–-2.svg
  static/images/bar-chart-do.svg
  static/images/bar-chart-dont-–-2.svg
  static/images/bar-chart-dont.svg
  static/images/bar-chart-horizontal.svg
  static/images/bar-chart-vertical.svg
  static/images/bar-chart.svg
  static/images/binary-color-palette.svg
  static/images/dashboard-layout.svg
  static/images/dashboard.svg
  static/images/display-metrics-–-movement.svg
  static/images/display-metrics.svg
  static/images/display.svg
  static/images/donut-chart-do.svg
  static/images/donut-chart-don-t-–-2.svg
  static/images/donut-chart-don-t.svg
  static/images/donut-chart-–-annotation.svg
  static/images/donut-chart-–-legend.svg
  static/images/donut-chart.svg
  static/images/donut.svg
  static/images/drill-down-2.svg
  static/images/drill-down.svg
  static/images/global-filter.svg
  static/images/grouped-bar-chart.svg
  static/images/heatmap-2.svg
  static/images/heatmap-color-palette.svg
  static/images/heatmap.svg
  static/images/individual-filter.svg
  static/images/layout-and-structure-2.svg
  static/images/layout-and-structure.svg
  static/images/line-chart-annotation.svg
  static/images/line-chart-color-palette.svg
  static/images/line-chart-color-sequence.svg
  static/images/line-chart-color.svg
  static/images/line-chart-do.svg
  static/images/line-chart-dont.svg
  static/images/line-chart-example.svg
  static/images/line-chart-legend.svg
  static/images/line-chart.svg
  static/images/pie.svg
  static/images/responsiveness-desktop-format.svg
  static/images/responsiveness-mobile-format.svg
  static/images/responsiveness.svg
  static/images/stacked-bar-chart.svg
  static/images/stacked-bar-color-palette.svg
  static/images/stacked-bar.svg
  static/images/vertical-column-chart.svg
Labels: netlify-cms/pending_publish
